services:
  - type: web
    name: vaakbhav
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
